POST http://localhost:8000/api/register
Content-Type: application/json

{
    "city": "Mountain View",
    "country": "Australia",
    "email": "john@gmail.com",
    "firstName": "Jon",
    "involvement": "Seeking employment",
    "lastName": "Doe",
    "mobileNumber": "+61102321654",
    "postcode": "",
    "province": "Northern Territory",
    "referral": "From relative.",
    "specialties": ["Artificial Integinece"]
}
